#!/usr/bin/env bash
#
# echo_agent.sh — a trivial demo agent backend (no LLM, no API key).
#
# It reads the task from the environment variables the runner provides and
# appends a Markdown section to CHANGES_FROM_AGENT.md in the current directory
# (which is the cloned repo). That file change is what the runner commits and
# turns into a draft PR — so this proves the whole pipeline end to end without
# any model or network call.
#
# Use it by pointing AGENT_CMD at this script, e.g. in your .env:
#   AGENT_CMD=/absolute/path/to/examples/echo_agent.sh
set -euo pipefail

out="CHANGES_FROM_AGENT.md"

{
  echo "## ${TASK_KEY:-UNKNOWN}: ${TASK_SUMMARY:-(no summary)}"
  echo
  echo "_Generated by echo_agent.sh (demo backend, no LLM)._"
  echo
  echo "Task description:"
  echo
  echo "${TASK_DESCRIPTION:-(no description)}"
  echo
} >>"$out"

echo "echo_agent: appended a section to $out for ${TASK_KEY:-UNKNOWN}"
